import type { Localizer } from "../../localization/localizer";
import { Dict } from "../../platform/dict";
import { Error } from "../../platform/error";
import { List, type ReadonlyList } from "../../platform/list";
import { StringUtils as SU } from "../../platform/string";
import { UniqueSet } from "../../platform/uniqueset";
import type {
  ActionCallSiteEntry,
  ActionRef,
  BrainActionResolver,
  IConversionRegistry,
  IOperatorOverloads,
  ITypeRegistry,
  PageMetadata,
  TypeId,
  UnlinkedBrainProgram,
} from "../../runtime";
import { anyVariableInit, CoreHostActions } from "../../runtime";
import { BYTECODE_VERSION, type FunctionBytecode, type Instr, Op } from "../../runtime/bytecode";
import { NIL_VALUE, TRUE_VALUE, type Value } from "../../runtime/value";
import type { IBrainDef, IBrainPageDef, IBrainRuleDef, IBrainTileDef, ITileCatalog } from "../interfaces";
import { CoreCapabilityBits, RuleSide, RuleTriggerMode } from "../interfaces";
import {
  availableWhenResultType,
  collectRuleHierarchyCapabilities,
  collectRuleHierarchyOutputKeys,
} from "../language-service/tile-suggestions";
import { childRulePath, rootRulePath } from "../rule-path";
import { ConstantPool } from "./constant-pool";
import { type BrainBuildDiagnostic, type BrainBuildResult, type DiagParams, diagnosticSeverity } from "./diagnostics";
import { BytecodeEmitter } from "./emitter";
import { computeExpectedTypes } from "./expected-types";
import { computeInferredTypes } from "./inferred-types";
import {
  parseBrainTiles,
  validateCapabilityRequirements,
  validateOutputProviders,
  validatePrecedingSiblingConsumers,
  validateTilePlacement,
  validateTriggerMode,
  validateWhenResultConsumers,
} from "./parser";
import { type CompilationDiag, ExprCompiler } from "./rule-compiler";
import { acceptExprVisitor, type Expr, type ParseDiag, type TypeEnv, type TypeInfo, type TypeInfoDiag } from "./types";

// Manual character-by-character iteration instead of String.replace() for
// Roblox-TS compatibility -- Roblox-TS doesn't support regex or string.replace.
function replaceAllSlashes(str: string): string {
  let result = "";
  const len = SU.length(str);
  for (let i = 0; i < len; i++) {
    const charCode = SU.charCodeAt(str, i);
    // "/" is ASCII 47
    result += charCode === 47 ? "_" : SU.fromCharCode(charCode);
  }
  return result;
}

/**
 * True when `expr` is exactly a sensor tile whose def carries the
 * {@link CoreCapabilityBits.PresenceGated} capability. Used to select
 * `WHEN_END_PRESENT` for a rule whose WHEN root is a bare presence-gated value
 * sensor; a sensor nested inside an expression is not the root and reports
 * false.
 */
function isBarePresenceGatedSensor(expr: Expr): boolean {
  return expr.kind === "sensor" && expr.tileDef.capabilities().get(CoreCapabilityBits.PresenceGated) === 1;
}

/** `params` carrying `rulePath`, the rule the diagnostic was reported in. */
function withRulePath(params: DiagParams | undefined, rulePath: string): DiagParams {
  return params ? { ...params, rulePath } : { rulePath };
}

/**
 * Result of compiling a single rule.
 */
interface RuleCompileResult {
  /** Generated bytecode for this rule */
  code: List<Instr>;

  /** Variable names used by this rule (for LOAD_VAR_SLOT/STORE_VAR_SLOT) */
  variableNames: ReadonlyList<string>;

  /** Function IDs of child rules that the parent spawns as fibers */
  childFuncIds: List<number>;
}

/**
 * BrainCompiler compiles an entire Brain definition into a single BrainProgram.
 *
 * Architecture:
 * - Each rule becomes a single function in the program
 * - Functions are assigned IDs in depth-first traversal order
 * - Parent rules spawn their child rules as fibers after the DO section completes
 * - All rules share a single constant pool
 * - Variables are resolved at Brain level (shared across all rules)
 *
 * Function layout:
 * ```
 * func[rule]:
 *   WHEN_START
 *   ... when bytecode ...
 *   WHEN_END               ; jumps to skip_label if false
 *   DO_START
 *   ... do bytecode ...
 *   DO_END
 *   SPAWN_RULE child_rule_0  ; spawn children in order, fire-and-forget
 *   SPAWN_RULE child_rule_1
 *   ...
 * skip_label:
 *   RET
 * ```
 */
export class BrainCompiler {
  private constantPool: ConstantPool;
  private functions: List<FunctionBytecode>;
  private ruleIndex: Dict<string, number>;
  /** Set of function ids that are rule entries (i.e. compiled from an `IBrainRuleDef`). */
  private ruleFuncIds: UniqueSet<number>;
  /** Mapping from a rule's funcId to its enclosing parent rule's funcId. Roots have no entry. */
  private ruleAncestors: Dict<number, number>;
  private pages: List<PageMetadata>;
  private nextFuncId: number;
  private catalogs: ReadonlyList<ITileCatalog>;
  private conversions: IConversionRegistry;
  /** Resolves action descriptors to bindings (host vs bytecode) at compile time */
  private actionResolver: BrainActionResolver;
  /** Type registry used during inference to resolve struct field ids from object types */
  private typeRegistry: ITypeRegistry;
  /** Locale the build's diagnostics name tiles in */
  private localizer: Localizer;
  /** Operator overload table of the brain under compilation, used to type WHEN expressions. */
  private operatorOverloads?: IOperatorOverloads;
  /** Global variable name pool for LOAD_VAR_SLOT/STORE_VAR_SLOT instructions */
  private variableNames: List<string>;
  /** Maps variable names to their index in variableNames */
  private variableIndices: Dict<string, number>;
  /** Data type each variable slot was minted at, keyed by variable name */
  private variableTypes: Dict<string, TypeId>;
  /** Per-slot starting-value index into the value constant pool, parallel to variableNames */
  private variableInitValues: List<number>;
  /** Variable name/type pairs already reported as a slot-sharing conflict */
  private reportedVariableConflicts: Dict<string, boolean>;
  /** Program-local action refs shared across all compiled rules */
  private actionRefs: List<ActionRef>;
  /** Maps action keys to their program-local slot */
  private actionIndices: Dict<string, number>;
  /** Counter for unique call-site IDs (shared across all rules for uniqueness) */
  private nextCallSiteIdCounter: { value: number };
  /** Type-table indices pinned as tree-shaker roots for host-produced struct values */
  private pinnedTypeIndices: UniqueSet<number>;
  /** Code-generation diagnostics collected across all compiled rules. */
  private compileDiags: List<BrainBuildDiagnostic>;

  constructor(
    catalogs: ReadonlyList<ITileCatalog>,
    conversions: IConversionRegistry,
    actionResolver: BrainActionResolver,
    typeRegistry: ITypeRegistry,
    localizer: Localizer
  ) {
    this.constantPool = new ConstantPool(typeRegistry);
    this.functions = List.empty();
    this.ruleIndex = Dict.empty();
    this.ruleFuncIds = new UniqueSet<number>();
    this.ruleAncestors = Dict.empty();
    this.pages = List.empty();
    this.nextFuncId = 0;
    this.catalogs = catalogs;
    this.conversions = conversions;
    this.actionResolver = actionResolver;
    this.typeRegistry = typeRegistry;
    this.localizer = localizer;
    this.variableNames = List.empty();
    this.variableIndices = Dict.empty();
    this.variableTypes = Dict.empty();
    this.variableInitValues = List.empty();
    this.reportedVariableConflicts = Dict.empty();
    this.actionRefs = List.empty();
    this.actionIndices = Dict.empty();
    this.nextCallSiteIdCounter = { value: 1 };
    this.pinnedTypeIndices = new UniqueSet<number>();
    this.compileDiags = List.empty();
  }

  /** Code-generation diagnostics collected during the last {@link compile}. */
  diagnostics(): ReadonlyList<BrainBuildDiagnostic> {
    return this.compileDiags;
  }

  /**
   * Compile an entire Brain definition into a single BrainProgram.
   *
   * @param brainDef - The brain definition to compile
   * @returns A complete BrainProgram ready for execution
   */
  compile(brainDef: IBrainDef): UnlinkedBrainProgram {
    // Reset state for fresh compilation
    this.constantPool = new ConstantPool(this.typeRegistry);
    this.functions = List.empty();
    this.ruleIndex = Dict.empty();
    this.ruleFuncIds = new UniqueSet<number>();
    this.ruleAncestors = Dict.empty();
    this.pages = List.empty();
    this.nextFuncId = 0;
    this.variableNames = List.empty();
    this.variableIndices = Dict.empty();
    this.variableTypes = Dict.empty();
    this.variableInitValues = List.empty();
    this.reportedVariableConflicts = Dict.empty();
    this.actionRefs = List.empty();
    this.actionIndices = Dict.empty();
    this.nextCallSiteIdCounter = { value: 0 };
    this.pinnedTypeIndices = new UniqueSet<number>();
    this.compileDiags = List.empty();
    this.operatorOverloads = brainDef.servicesOperatorOverloads();

    // First pass: assign function IDs to all rules (depth-first)
    const pageList = brainDef.pages();
    for (let pageIdx = 0; pageIdx < pageList.size(); pageIdx++) {
      const pageDef = pageList.get(pageIdx);
      this.assignFuncIds(pageDef, pageIdx);
    }

    // Second pass: compile all rules with known function IDs
    for (let pageIdx = 0; pageIdx < pageList.size(); pageIdx++) {
      const pageDef = pageList.get(pageIdx);
      this.compilePage(pageDef, pageIdx);
    }

    return {
      version: BYTECODE_VERSION,
      functions: this.functions,
      constantPools: this.constantPool.toPools(),
      types: this.constantPool.typeEntries(),
      variableNames: this.variableNames,
      ...(anyVariableInit(this.variableInitValues) ? { variableInitValues: this.variableInitValues } : {}),
      entryPoint: 0, // First page's first rule
      ruleIndex: this.ruleIndex,
      ruleFuncIds: this.ruleFuncIds,
      ruleAncestors: this.ruleAncestors,
      actionRefs: this.actionRefs,
      pages: this.pages,
      pinnedTypeIndices: this.pinnedTypeIndices,
    };
  }

  /**
   * First pass: Assign function IDs to all rules in depth-first order. This
   * allows us to know child function IDs before compiling parents.
   */
  private assignFuncIds(pageDef: IBrainPageDef, pageIdx: number): void {
    const rootRuleFuncIds = List.empty<number>();
    const rules = pageDef.children();

    for (let ruleIdx = 0; ruleIdx < rules.size(); ruleIdx++) {
      const ruleDef = rules.get(ruleIdx);
      const funcId = this.assignFuncIdToRule(ruleDef, rootRulePath(pageIdx, ruleIdx), undefined);
      rootRuleFuncIds.push(funcId);
    }

    this.pages.push({
      pageIndex: pageIdx,
      pageName: pageDef.name(),
      pageId: pageDef.pageId(),
      rootRuleFuncIds,
      actionCallSites: List.empty(),
    });
  }

  /**
   * Recursively assign function IDs to a rule and its children.
   */
  private assignFuncIdToRule(ruleDef: IBrainRuleDef, rulePath: string, parentFuncId: number | undefined): number {
    const funcId = this.nextFuncId++;
    this.ruleIndex.set(rulePath, funcId);
    this.ruleFuncIds.add(funcId);
    if (parentFuncId !== undefined) {
      this.ruleAncestors.set(funcId, parentFuncId);
    }

    // Reserve slot in functions list (will be filled during compile pass)
    this.functions.push({
      code: List.empty(),
      numParams: 0,
      name: `rule_${replaceAllSlashes(rulePath)}`,
    });

    // Assign IDs to children
    const children = ruleDef.children();
    for (let childIdx = 0; childIdx < children.size(); childIdx++) {
      const childDef = children.get(childIdx);
      this.assignFuncIdToRule(childDef, childRulePath(rulePath, childIdx), funcId);
    }

    return funcId;
  }

  /**
   * Second pass: Compile all rules in a page, then collect action callsites.
   */
  private compilePage(pageDef: IBrainPageDef, pageIdx: number): void {
    const rules = pageDef.children();
    const pageMetadata = this.pages.get(pageIdx)!;

    for (let ruleIdx = 0; ruleIdx < rules.size(); ruleIdx++) {
      const ruleDef = rules.get(ruleIdx);
      this.compileRule(ruleDef, rootRulePath(pageIdx, ruleIdx), ruleIdx);
    }

    // Collect all action callsites from all compiled rules in this page
    const visitedFuncs = new UniqueSet<number>();
    this.collectActionCallSites(pageMetadata.rootRuleFuncIds, visitedFuncs, pageMetadata.actionCallSites);
  }

  /**
   * Recursively collect all action call sites from a set of rule functions and
   * their children (via SPAWN_RULE instructions). Host call sites
   * (`HOST_ACTION_CALL` / `HOST_ACTION_CALL_ASYNC`) are recorded with their
   * stable `actionId`; bytecode call sites (`ACTION_CALL` / `ACTION_CALL_ASYNC`)
   * with their program-local `actionSlot`.
   */
  private collectActionCallSites(
    funcIds: List<number>,
    visitedFuncs: UniqueSet<number>,
    out: List<ActionCallSiteEntry>
  ): void {
    for (let i = 0; i < funcIds.size(); i++) {
      const funcId = funcIds.get(i)!;
      if (visitedFuncs.has(funcId)) continue;
      visitedFuncs.add(funcId);

      const fn = this.functions.at(funcId);
      if (!fn) continue;

      const childFuncIds = List.empty<number>();
      for (let pc = 0; pc < fn.code.size(); pc++) {
        const ins = fn.code.get(pc)!;
        if (ins.op === Op.ACTION_CALL || ins.op === Op.ACTION_CALL_ASYNC) {
          out.push({ binding: "bytecode", actionSlot: ins.a ?? 0, callSiteId: ins.c ?? 0 });
        } else if (ins.op === Op.HOST_ACTION_CALL || ins.op === Op.HOST_ACTION_CALL_ASYNC) {
          out.push({ binding: "host", actionId: ins.a ?? 0, callSiteId: ins.c ?? 0 });
        } else if (ins.op === Op.SPAWN_RULE) {
          childFuncIds.push(ins.a ?? 0);
        }
      }

      // Recurse into child rules
      if (childFuncIds.size() > 0) {
        this.collectActionCallSites(childFuncIds, visitedFuncs, out);
      }
    }
  }

  /**
   * Compile a single rule and its children recursively.
   *
   * @param ruleDef - The rule to compile.
   * @param rulePath - The rule's `pageIndex/ruleIndex[/childIndex...]` path.
   * @param siblingIndex - The rule's zero-based position among the rules at its
   *   own nesting level.
   */
  private compileRule(ruleDef: IBrainRuleDef, rulePath: string, siblingIndex: number): void {
    const funcId = this.ruleIndex.get(rulePath);
    if (funcId === undefined) {
      throw new Error(`BrainCompiler: No function ID assigned for rule at ${rulePath}`);
    }

    const children = ruleDef.children();

    // Collect child function IDs
    const childFuncIds = List.empty<number>();
    for (let childIdx = 0; childIdx < children.size(); childIdx++) {
      const childFuncId = this.ruleIndex.get(childRulePath(rulePath, childIdx));
      if (childFuncId !== undefined) {
        childFuncIds.push(childFuncId);
      }
    }

    // Compile this rule's WHEN and DO
    const fn = this.functions.get(funcId)!;
    fn.code = this.compileRuleBody(ruleDef, childFuncIds, rulePath, siblingIndex).code;

    // Recursively compile children
    for (let childIdx = 0; childIdx < children.size(); childIdx++) {
      const childDef = children.get(childIdx);
      this.compileRule(childDef, childRulePath(rulePath, childIdx), childIdx);
    }
  }

  /**
   * Push each diagnostic as a build diagnostic at its classified severity,
   * attributed to the rule at `rulePath`.
   */
  private pushParseDiags(diags: ReadonlyList<ParseDiag>, rulePath: string): void {
    for (let i = 0; i < diags.size(); i++) {
      const diag = diags.get(i)!;
      this.compileDiags.push({
        code: diag.code,
        severity: diagnosticSeverity(diag.code),
        message: diag.message,
        params: withRulePath(diag.params, rulePath),
      });
    }
  }

  /**
   * Push the error-severity entries of a side's inference diagnostics,
   * attributed to the rule at `rulePath`.
   */
  private pushBlockingTypeErrors(diags: ReadonlyList<TypeInfoDiag>, rulePath: string): void {
    for (let i = 0; i < diags.size(); i++) {
      const diag = diags.get(i)!;
      if (diagnosticSeverity(diag.code) === "error") {
        this.compileDiags.push({
          code: diag.code,
          severity: "error",
          message: diag.message,
          params: withRulePath(diag.params, rulePath),
        });
      }
    }
  }

  /**
   * Compile a rule's WHEN/DO body and emit CALL instructions for children.
   */
  private compileRuleBody(
    ruleDef: IBrainRuleDef,
    childFuncIds: List<number>,
    rulePath: string,
    siblingIndex: number
  ): RuleCompileResult {
    const whenTiles = ruleDef.when().tiles();
    const doTiles = ruleDef.do().tiles();

    // A tile whose placement excludes the side it appears on blocks the build.
    this.pushParseDiags(validateTilePlacement(whenTiles, RuleSide.When, this.localizer), rulePath);
    this.pushParseDiags(validateTilePlacement(doTiles, RuleSide.Do, this.localizer), rulePath);

    // A tile reporting on the preceding sibling rule blocks the build in the
    // first rule at its level, which has no rule above it.
    this.pushParseDiags(validatePrecedingSiblingConsumers(whenTiles, siblingIndex > 0, this.localizer), rulePath);
    this.pushParseDiags(validatePrecedingSiblingConsumers(doTiles, siblingIndex > 0, this.localizer), rulePath);

    this.pushParseDiags(validateTriggerMode(ruleDef.trigger(), siblingIndex > 0), rulePath);

    // An output tile with no providing sensor in the rule hierarchy (this
    // rule's WHEN and DO sides plus every ancestor rule's) blocks the build.
    const providedOutputKeys = collectRuleHierarchyOutputKeys(ruleDef);
    this.pushParseDiags(validateOutputProviders(whenTiles, providedOutputKeys, this.localizer), rulePath);
    this.pushParseDiags(validateOutputProviders(doTiles, providedOutputKeys, this.localizer), rulePath);

    // A tile whose required capabilities no tile in the rule hierarchy
    // provides blocks the build.
    const availableCapabilities = collectRuleHierarchyCapabilities(ruleDef);
    this.pushParseDiags(
      validateCapabilityRequirements(whenTiles, availableCapabilities, this.catalogs, this.localizer),
      rulePath
    );
    this.pushParseDiags(
      validateCapabilityRequirements(doTiles, availableCapabilities, this.catalogs, this.localizer),
      rulePath
    );

    // A tile declaring `consumesWhenResult(T)` with no compatible WHEN result
    // available on its side (the enclosing rule's result for the WHEN side,
    // this rule's own for the DO side) blocks the build.
    const whenSideWhenResult = availableWhenResultType(
      ruleDef,
      RuleSide.When,
      this.operatorOverloads,
      this.conversions
    );
    const doSideWhenResult = availableWhenResultType(ruleDef, RuleSide.Do, this.operatorOverloads, this.conversions);
    this.pushParseDiags(
      validateWhenResultConsumers(whenTiles, whenSideWhenResult, this.conversions, this.typeRegistry, this.localizer),
      rulePath
    );
    this.pushParseDiags(
      validateWhenResultConsumers(doTiles, doSideWhenResult, this.conversions, this.typeRegistry, this.localizer),
      rulePath
    );

    // A rule's parse diagnostics precede the compilation diagnostics its tiles yield.
    const whenParseResult = parseBrainTiles(whenTiles, this.localizer, -1, 0);
    const doParseResult = parseBrainTiles(doTiles, this.localizer, -1, 0, whenParseResult.nextNodeId);
    this.pushParseDiags(whenParseResult.diags, rulePath);
    this.pushParseDiags(doParseResult.diags, rulePath);

    // Type checking
    const typeEnv: TypeEnv = new Dict<number, TypeInfo>();

    for (let i = 0; i < whenParseResult.exprs.size(); i++) {
      computeExpectedTypes(whenParseResult.exprs.get(i), typeEnv);
    }
    for (let i = 0; i < doParseResult.exprs.size(); i++) {
      computeExpectedTypes(doParseResult.exprs.get(i), typeEnv);
    }

    for (let i = 0; i < whenParseResult.exprs.size(); i++) {
      this.pushBlockingTypeErrors(
        computeInferredTypes(
          whenParseResult.exprs.get(i),
          this.catalogs,
          typeEnv,
          this.conversions,
          this.typeRegistry,
          this.localizer
        ),
        rulePath
      );
    }
    for (let i = 0; i < doParseResult.exprs.size(); i++) {
      this.pushBlockingTypeErrors(
        computeInferredTypes(
          doParseResult.exprs.get(i),
          this.catalogs,
          typeEnv,
          this.conversions,
          this.typeRegistry,
          this.localizer
        ),
        rulePath
      );
    }

    // Create emitter for this rule's function
    const emitter = new BytecodeEmitter();
    const endLabel = emitter.label();

    // Emit WHEN section. A bare presence-gated value sensor as the WHEN root
    // gates DO on presence (non-nil); every other WHEN gates on truthiness. A
    // `when`-mode rule with no WHEN condition captures no WHEN result and fires
    // unconditionally: it emits no WHEN section, so getWhenResult in its DO reads
    // no own slot and falls through to an enclosing rule's captured result. An
    // `otherwise` or `then` rule always emits the section: its arming read is
    // the WHEN value when the expression is empty.
    const whenIsEmpty = whenParseResult.exprs.get(0).kind === "empty";
    const presenceGated = !whenIsEmpty && isBarePresenceGatedSensor(whenParseResult.exprs.get(0));
    const trigger = ruleDef.trigger();
    if (trigger === RuleTriggerMode.When) {
      if (!whenIsEmpty) {
        emitter.whenStart();
        this.emitExprs(whenParseResult.exprs, emitter, typeEnv, true, rulePath, RuleSide.When, whenTiles);
        if (presenceGated) {
          emitter.whenEndPresent(endLabel);
        } else {
          emitter.whenEnd(endLabel);
        }
      }
    } else {
      emitter.whenStart();
      this.emitTriggerPrologue(emitter, trigger);
      if (!whenIsEmpty) {
        // The arming read short-circuits the expression: an unarmed rule stands
        // NIL in the expression's place, which both gate forms read as "did not
        // fire", so the gate still runs and still writes the record.
        const unarmedLabel = emitter.label();
        const gateLabel = emitter.label();
        emitter.jmpIfFalse(unarmedLabel);
        this.emitExprs(whenParseResult.exprs, emitter, typeEnv, true, rulePath, RuleSide.When, whenTiles);
        emitter.jmp(gateLabel);
        emitter.mark(unarmedLabel);
        emitter.pushConst(this.constantPool.addOther(NIL_VALUE));
        emitter.mark(gateLabel);
      }
      this.emitTriggerGate(emitter, trigger, presenceGated, endLabel);
    }

    // Emit DO section
    emitter.doStart();
    this.emitExprs(doParseResult.exprs, emitter, typeEnv, false, rulePath, RuleSide.Do, doTiles);
    emitter.doEnd();

    // Spawn each child rule in its own fiber (only if WHEN was true, i.e., we're
    // before endLabel). Each child rule runs concurrently with its siblings and
    // resumes across the think boundary; the parent does not wait for it.
    for (let i = 0; i < childFuncIds.size(); i++) {
      const childFuncId = childFuncIds.get(i)!;
      emitter.spawnRule(childFuncId);
    }

    // Mark end label (jumped to if WHEN was false - skips DO and children)
    emitter.mark(endLabel);

    // Push NIL as return value (RET expects a value on the stack)
    // Rule functions don't return meaningful values - caller always discards the result
    const nilIdx = this.constantPool.addOther(NIL_VALUE);
    emitter.pushConst(nilIdx);

    // Return
    emitter.ret();

    return {
      code: emitter.finalize(),
      variableNames: this.variableNames,
      childFuncIds,
    };
  }

  /**
   * Emit the arming read that opens the WHEN section of a rule whose trigger
   * mode is not `when`, leaving its boolean answer on the operand stack.
   *
   * An `otherwise` rule reads the `otherwise` host sensor synchronously. A
   * `then` rule dispatches the rule-trigger host action asynchronously and
   * awaits it, so a rule whose subject is still in flight parks here.
   */
  private emitTriggerPrologue(emitter: BytecodeEmitter, trigger: RuleTriggerMode): void {
    const callSiteId = this.nextCallSiteIdCounter.value++;
    if (trigger === RuleTriggerMode.Otherwise) {
      emitter.hostActionCall(CoreHostActions.Otherwise.actionId, 0, callSiteId);
      return;
    }
    emitter.hostActionCallAsync(CoreHostActions.RuleTrigger.actionId, 0, callSiteId);
    emitter.await();
  }

  /**
   * Emit the WHEN gate closing a rule whose trigger mode is not `when`. An
   * `otherwise` rule takes the chain variant of the gate its expression selects,
   * so its record carries the ladder outcome; a `then` rule takes the ordinary
   * variant.
   *
   * @param presenceGated - Whether the rule's WHEN expression selected the
   *   presence gate.
   * @param endLabel - Label past the DO section, taken when the gate does not fire.
   */
  private emitTriggerGate(
    emitter: BytecodeEmitter,
    trigger: RuleTriggerMode,
    presenceGated: boolean,
    endLabel: number
  ): void {
    if (trigger === RuleTriggerMode.Otherwise) {
      if (presenceGated) {
        emitter.whenEndPresentChain(endLabel);
      } else {
        emitter.whenEndChain(endLabel);
      }
      return;
    }
    if (presenceGated) {
      emitter.whenEndPresent(endLabel);
    } else {
      emitter.whenEnd(endLabel);
    }
  }

  /**
   * Emit bytecode for a list of expressions. Uses the global variable pool for
   * all variable references.
   *
   * @param exprs - List of expressions to emit (always has at least one
   * element)
   * @param emitter - Bytecode emitter
   * @param typeEnv - Type environment
   * @param isWhenContext - If true, empty expressions push TRUE; if false, they
   * emit nothing
   * @param rulePath - Rule path of the enclosing rule, in `page/rule[/child]` form
   * @param ruleSide - Rule side being emitted
   * @param sideTiles - Tiles of the side being emitted, indexed by expression span position
   */
  private emitExprs(
    exprs: ReadonlyList<Expr>,
    emitter: BytecodeEmitter,
    typeEnv: TypeEnv,
    isWhenContext: boolean,
    rulePath: string,
    ruleSide: RuleSide,
    sideTiles: ReadonlyList<IBrainTileDef>
  ): void {
    const context = {
      variableIndices: this.variableIndices,
      variableNames: this.variableNames,
      variableTypes: this.variableTypes,
      variableInitValues: this.variableInitValues,
      reportedVariableConflicts: this.reportedVariableConflicts,
      actionIndices: this.actionIndices,
      actionRefs: this.actionRefs,
      actionResolver: this.actionResolver,
      typeEnv,
      constantPool: this.constantPool,
      pinnedTypeIndices: this.pinnedTypeIndices,
      typeRegistry: this.typeRegistry,
      catalogs: this.catalogs,
      nextCallSiteId: this.nextCallSiteIdCounter,
      rulePath,
      ruleSide,
      sideTiles,
      diags: List.empty<CompilationDiag>(),
    };

    const compiler = new ExprCompiler(emitter, context);

    // Only the first expression is emitted; every later one is parser recovery
    // output that code generation discards.
    for (let i = 1; i < exprs.size(); i++) {
      const extra = exprs.get(i);
      const reason = extra.kind === "errorExpr" ? extra.message : "Expression after the side's first expression";
      const tileIndex = extra.kind === "errorExpr" ? extra.span?.from : undefined;
      compiler.reportDroppedExpr(extra.nodeId, tileIndex, reason);
    }

    const expr = exprs.get(0);
    if (expr.kind === "empty") {
      // Empty WHEN means "always true"; empty DO means "do nothing".
      if (isWhenContext) {
        const trueIdx = this.constantPool.addOther(TRUE_VALUE);
        emitter.pushConst(trueIdx);
      }
    } else {
      acceptExprVisitor(expr, compiler);
    }

    for (let i = 0; i < context.diags.size(); i++) {
      const diag = context.diags.get(i)!;
      this.compileDiags.push({
        code: diag.code,
        severity: diag.severity,
        message: diag.message,
        params: withRulePath(diag.params, rulePath),
      });
    }
  }
}

/**
 * Compile an entire brain definition into a single program. This is the main
 * entry point for whole-brain compilation.
 *
 * @param brainDef - The brain definition to compile
 * @param catalogs - Tile catalogs for type resolution
 * @param conversions - Conversion registry used during type inference
 * @param actionResolver - Resolves each action's binding (host vs bytecode) so
 *   the compiler emits host calls by stable id and bytecode calls by slot
 * @param typeRegistry - Type registry used during inference to resolve struct
 *   field ids from a field-access object's type
 * @returns A complete BrainProgram
 */
export function compileBrain(
  brainDef: IBrainDef,
  catalogs: ReadonlyList<ITileCatalog>,
  conversions: IConversionRegistry,
  actionResolver: BrainActionResolver,
  typeRegistry: ITypeRegistry
): BrainBuildResult<UnlinkedBrainProgram> {
  const compiler = new BrainCompiler(catalogs, conversions, actionResolver, typeRegistry, brainDef.servicesLocalizer());
  const program = compiler.compile(brainDef);
  return { program, diagnostics: compiler.diagnostics() };
}
